-- Generated by Envision Gui2Lua, VER-1, 0-22. (THAT IS PLUGIN NOT A SKIDDED SCRIPT  )

local Instances = {
	YE_HUB = Instance.new("ScreenGui"),
	UIs = Instance.new("Folder"),
	SCPCBRP = Instance.new("Frame"),
	B1 = Instance.new("TextButton"),
	TextBox = Instance.new("TextBox"),
	LeftMenu = Instance.new("Frame"),
	TextButton = Instance.new("TextButton"),
	UICorner = Instance.new("UICorner"),
	B2 = Instance.new("TextButton"),
	CloseButton = Instance.new("TextButton"),
	Special_Thanks = Instance.new("TextLabel"),
	B3 = Instance.new("TextButton"),
	TextBox_2 = Instance.new("TextBox"),
	DiscordButton = Instance.new("TextButton"),
	EREPO = Instance.new("Frame"),
	B1_2 = Instance.new("TextButton"),
	LeftMenu_2 = Instance.new("Frame"),
	TextButton_2 = Instance.new("TextButton"),
	UICorner_2 = Instance.new("UICorner"),
	CloseButton_2 = Instance.new("TextButton"),
	B2_2 = Instance.new("TextButton"),
	B3_2 = Instance.new("TextButton"),
	DiscordButton_2 = Instance.new("TextButton"),
	BSBD = Instance.new("Frame"),
	B1_3 = Instance.new("TextButton"),
	LeftMenu_3 = Instance.new("Frame"),
	TextButton_3 = Instance.new("TextButton"),
	UICorner_3 = Instance.new("UICorner"),
	CloseButton_3 = Instance.new("TextButton"),
	DiscordButton_3 = Instance.new("TextButton"),
	SB_2 = Instance.new("Frame"),
	B1_4 = Instance.new("TextButton"),
	LeftMenu_4 = Instance.new("Frame"),
	TextButton_4 = Instance.new("TextButton"),
	UICorner_4 = Instance.new("UICorner"),
	B2_3 = Instance.new("TextButton"),
	TextLabel = Instance.new("TextLabel"),
	CloseButton_4 = Instance.new("TextButton"),
	DiscordButton_4 = Instance.new("TextButton"),
	TextLabel_2 = Instance.new("TextLabel"),
	tb1 = Instance.new("TextButton"),
	tb2 = Instance.new("TextButton"),
}

Instances.YE_HUB.Name = "YE_HUB"
Instances.YE_HUB.Parent = game.Players.LocalPlayer.PlayerGui
Instances.YE_HUB.ResetOnSpawn = false

Instances.UIs.Name = "UIs"
Instances.UIs.Parent = Instances.YE_HUB

Instances.SCPCBRP.Name = "SCPCBRP"
Instances.SCPCBRP.Size = UDim2.new(0, 528, 0, 253)
Instances.SCPCBRP.Visible = false
Instances.SCPCBRP.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.SCPCBRP.Position = UDim2.new(0.297628164, 0, 0.297770709, 0)
Instances.SCPCBRP.BorderSizePixel = 0
Instances.SCPCBRP.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.SCPCBRP.Parent = Instances.UIs

Instances.B1.Name = "B1"
Instances.B1.Size = UDim2.new(0, 82, 0, 32)
Instances.B1.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1.Position = UDim2.new(0.288727283, 0, 0.0197628457, 0)
Instances.B1.BorderSizePixel = 0
Instances.B1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B1.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1.Text = "Change All UserNames"
Instances.B1.TextWrapped = true
Instances.B1.TextSize = 14
Instances.B1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B1.TextScaled = true
Instances.B1.Parent = Instances.SCPCBRP

Instances.TextBox.Name = "TextBox"
Instances.TextBox.Size = UDim2.new(0, 82, 0, 32)
Instances.TextBox.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextBox.Position = UDim2.new(1.08536589, 0, 0, 0)
Instances.TextBox.BorderSizePixel = 0
Instances.TextBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.TextBox.PlaceholderText = "UserName"
Instances.TextBox.TextSize = 14
Instances.TextBox.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextBox.Text = ""
Instances.TextBox.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextBox.ClearTextOnFocus = false
Instances.TextBox.Parent = Instances.B1

Instances.LeftMenu.Name = "LeftMenu"
Instances.LeftMenu.Size = UDim2.new(0, 139, 0, 253)
Instances.LeftMenu.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.LeftMenu.BorderSizePixel = 0
Instances.LeftMenu.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.LeftMenu.Parent = Instances.SCPCBRP

Instances.TextButton.Name = "TextButton"
Instances.TextButton.Size = UDim2.new(0, 140, 0, 37)
Instances.TextButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton.Position = UDim2.new(-0.00104545825, 0, 0, 0)
Instances.TextButton.BorderSizePixel = 0
Instances.TextButton.BackgroundColor3 = Color3.fromRGB(190, 190, 190)
Instances.TextButton.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton.Text = "General"
Instances.TextButton.TextWrapped = true
Instances.TextButton.TextSize = 14
Instances.TextButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextButton.TextScaled = true
Instances.TextButton.Parent = Instances.LeftMenu

Instances.UICorner.Name = "UICorner"
Instances.UICorner.Parent = Instances.SCPCBRP

Instances.B2.Name = "B2"
Instances.B2.Size = UDim2.new(0, 82, 0, 32)
Instances.B2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B2.Position = UDim2.new(0.288727283, 0, 0.17786561, 0)
Instances.B2.BorderSizePixel = 0
Instances.B2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B2.Text = "Get AK-47 & Level 5 KeyCard"
Instances.B2.TextWrapped = true
Instances.B2.TextSize = 14
Instances.B2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B2.TextScaled = true
Instances.B2.Parent = Instances.SCPCBRP

Instances.CloseButton.Name = "CloseButton"
Instances.CloseButton.Size = UDim2.new(0, 18, 0, 22)
Instances.CloseButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.CloseButton.BackgroundTransparency = 1
Instances.CloseButton.Position = UDim2.new(0.965909064, 0, 0.0197628457, 0)
Instances.CloseButton.BorderSizePixel = 0
Instances.CloseButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.CloseButton.TextColor3 = Color3.fromRGB(255, 0, 0)
Instances.CloseButton.Text = "X"
Instances.CloseButton.TextWrapped = true
Instances.CloseButton.TextSize = 14
Instances.CloseButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.CloseButton.TextScaled = true
Instances.CloseButton.Parent = Instances.SCPCBRP

Instances.Special_Thanks.Name = "Special Thanks"
Instances.Special_Thanks.Size = UDim2.new(0, 142, 0, 19)
Instances.Special_Thanks.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Special_Thanks.Position = UDim2.new(0.628787875, 0, 0.0197628457, 0)
Instances.Special_Thanks.BorderSizePixel = 0
Instances.Special_Thanks.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.Special_Thanks.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.Special_Thanks.Text = "(SPECIAL THANKS TO im.yet.cool_2)"
Instances.Special_Thanks.TextWrapped = true
Instances.Special_Thanks.TextSize = 14
Instances.Special_Thanks.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.Special_Thanks.TextScaled = true
Instances.Special_Thanks.Parent = Instances.SCPCBRP

Instances.B3.Name = "B3"
Instances.B3.Size = UDim2.new(0, 82, 0, 32)
Instances.B3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B3.Position = UDim2.new(0.288727283, 0, 0.343873531, 0)
Instances.B3.BorderSizePixel = 0
Instances.B3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B3.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B3.Text = "Lag Server"
Instances.B3.TextWrapped = true
Instances.B3.TextSize = 14
Instances.B3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B3.TextScaled = true
Instances.B3.Parent = Instances.SCPCBRP

Instances.TextBox_2.Name = "TextBox"
Instances.TextBox_2.Size = UDim2.new(0, 82, 0, 32)
Instances.TextBox_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextBox_2.Position = UDim2.new(1.08536589, 0, 0, 0)
Instances.TextBox_2.BorderSizePixel = 0
Instances.TextBox_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.TextBox_2.PlaceholderText = "How many items? ( *2 )"
Instances.TextBox_2.TextSize = 14
Instances.TextBox_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextBox_2.Text = ""
Instances.TextBox_2.TextWrapped = true
Instances.TextBox_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextBox_2.ClearTextOnFocus = false
Instances.TextBox_2.Parent = Instances.B3

Instances.DiscordButton.Name = "DiscordButton"
Instances.DiscordButton.Size = UDim2.new(0, 99, 0, 31)
Instances.DiscordButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton.Position = UDim2.new(-0.00189393945, 0, 0.877470374, 0)
Instances.DiscordButton.BorderSizePixel = 0
Instances.DiscordButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.DiscordButton.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton.Text = "Join Discord"
Instances.DiscordButton.TextWrapped = true
Instances.DiscordButton.TextSize = 14
Instances.DiscordButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.DiscordButton.TextScaled = true
Instances.DiscordButton.Parent = Instances.SCPCBRP

Instances.EREPO.Name = "EREPO"
Instances.EREPO.Size = UDim2.new(0, 528, 0, 253)
Instances.EREPO.Visible = false
Instances.EREPO.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.EREPO.Position = UDim2.new(0.297628164, 0, 0.297770709, 0)
Instances.EREPO.BorderSizePixel = 0
Instances.EREPO.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.EREPO.Parent = Instances.UIs

Instances.B1_2.Name = "B1"
Instances.B1_2.Size = UDim2.new(0, 82, 0, 32)
Instances.B1_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1_2.Position = UDim2.new(0.288727283, 0, 0.0197628457, 0)
Instances.B1_2.BorderSizePixel = 0
Instances.B1_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B1_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1_2.Text = "Kill everyone"
Instances.B1_2.TextWrapped = true
Instances.B1_2.TextSize = 14
Instances.B1_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B1_2.TextScaled = true
Instances.B1_2.Parent = Instances.EREPO

Instances.LeftMenu_2.Name = "LeftMenu"
Instances.LeftMenu_2.Size = UDim2.new(0, 139, 0, 253)
Instances.LeftMenu_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.LeftMenu_2.BorderSizePixel = 0
Instances.LeftMenu_2.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.LeftMenu_2.Parent = Instances.EREPO

Instances.TextButton_2.Name = "TextButton"
Instances.TextButton_2.Size = UDim2.new(0, 140, 0, 37)
Instances.TextButton_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton_2.Position = UDim2.new(-0.00104545825, 0, 0, 0)
Instances.TextButton_2.BorderSizePixel = 0
Instances.TextButton_2.BackgroundColor3 = Color3.fromRGB(190, 190, 190)
Instances.TextButton_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton_2.Text = "General"
Instances.TextButton_2.TextWrapped = true
Instances.TextButton_2.TextSize = 14
Instances.TextButton_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextButton_2.TextScaled = true
Instances.TextButton_2.Parent = Instances.LeftMenu_2

Instances.UICorner_2.Name = "UICorner"
Instances.UICorner_2.Parent = Instances.EREPO

Instances.CloseButton_2.Name = "CloseButton"
Instances.CloseButton_2.Size = UDim2.new(0, 18, 0, 22)
Instances.CloseButton_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.CloseButton_2.BackgroundTransparency = 1
Instances.CloseButton_2.Position = UDim2.new(0.965909064, 0, 0.0197628457, 0)
Instances.CloseButton_2.BorderSizePixel = 0
Instances.CloseButton_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.CloseButton_2.TextColor3 = Color3.fromRGB(255, 0, 0)
Instances.CloseButton_2.Text = "X"
Instances.CloseButton_2.TextWrapped = true
Instances.CloseButton_2.TextSize = 14
Instances.CloseButton_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.CloseButton_2.TextScaled = true
Instances.CloseButton_2.Parent = Instances.EREPO

Instances.B2_2.Name = "B2"
Instances.B2_2.Size = UDim2.new(0, 82, 0, 32)
Instances.B2_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B2_2.Position = UDim2.new(0.288727283, 0, 0.17786561, 0)
Instances.B2_2.BorderSizePixel = 0
Instances.B2_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B2_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B2_2.Text = "TP To End"
Instances.B2_2.TextWrapped = true
Instances.B2_2.TextSize = 14
Instances.B2_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B2_2.TextScaled = true
Instances.B2_2.Parent = Instances.EREPO

Instances.B3_2.Name = "B3"
Instances.B3_2.Size = UDim2.new(0, 82, 0, 32)
Instances.B3_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B3_2.Position = UDim2.new(0.289000005, 0, 0.354000002, 0)
Instances.B3_2.BorderSizePixel = 0
Instances.B3_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B3_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B3_2.Text = "Make server unplayable"
Instances.B3_2.TextWrapped = true
Instances.B3_2.TextSize = 14
Instances.B3_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B3_2.TextScaled = true
Instances.B3_2.Parent = Instances.EREPO

Instances.DiscordButton_2.Name = "DiscordButton"
Instances.DiscordButton_2.Size = UDim2.new(0, 99, 0, 31)
Instances.DiscordButton_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton_2.Position = UDim2.new(-0.00189393945, 0, 0.877470374, 0)
Instances.DiscordButton_2.BorderSizePixel = 0
Instances.DiscordButton_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.DiscordButton_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton_2.Text = "Join Discord"
Instances.DiscordButton_2.TextWrapped = true
Instances.DiscordButton_2.TextSize = 14
Instances.DiscordButton_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.DiscordButton_2.TextScaled = true
Instances.DiscordButton_2.Parent = Instances.EREPO

Instances.BSBD.Name = "BSBD"
Instances.BSBD.Size = UDim2.new(0, 528, 0, 253)
Instances.BSBD.Visible = false
Instances.BSBD.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.BSBD.Position = UDim2.new(0.297628164, 0, 0.297770709, 0)
Instances.BSBD.BorderSizePixel = 0
Instances.BSBD.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.BSBD.Parent = Instances.UIs

Instances.B1_3.Name = "B1"
Instances.B1_3.Size = UDim2.new(0, 82, 0, 32)
Instances.B1_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1_3.Position = UDim2.new(0.288727283, 0, 0.0197628457, 0)
Instances.B1_3.BorderSizePixel = 0
Instances.B1_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B1_3.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1_3.Text = "Bypass Anti-Cheat"
Instances.B1_3.TextWrapped = true
Instances.B1_3.TextSize = 14
Instances.B1_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B1_3.TextScaled = true
Instances.B1_3.Parent = Instances.BSBD

Instances.LeftMenu_3.Name = "LeftMenu"
Instances.LeftMenu_3.Size = UDim2.new(0, 139, 0, 253)
Instances.LeftMenu_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.LeftMenu_3.BorderSizePixel = 0
Instances.LeftMenu_3.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.LeftMenu_3.Parent = Instances.BSBD

Instances.TextButton_3.Name = "TextButton"
Instances.TextButton_3.Size = UDim2.new(0, 140, 0, 37)
Instances.TextButton_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton_3.Position = UDim2.new(-0.00104545825, 0, 0, 0)
Instances.TextButton_3.BorderSizePixel = 0
Instances.TextButton_3.BackgroundColor3 = Color3.fromRGB(190, 190, 190)
Instances.TextButton_3.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton_3.Text = "General"
Instances.TextButton_3.TextWrapped = true
Instances.TextButton_3.TextSize = 14
Instances.TextButton_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextButton_3.TextScaled = true
Instances.TextButton_3.Parent = Instances.LeftMenu_3

Instances.UICorner_3.Name = "UICorner"
Instances.UICorner_3.Parent = Instances.BSBD

Instances.CloseButton_3.Name = "CloseButton"
Instances.CloseButton_3.Size = UDim2.new(0, 18, 0, 22)
Instances.CloseButton_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.CloseButton_3.BackgroundTransparency = 1
Instances.CloseButton_3.Position = UDim2.new(0.965909064, 0, 0.0197628457, 0)
Instances.CloseButton_3.BorderSizePixel = 0
Instances.CloseButton_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.CloseButton_3.TextColor3 = Color3.fromRGB(255, 0, 0)
Instances.CloseButton_3.Text = "X"
Instances.CloseButton_3.TextWrapped = true
Instances.CloseButton_3.TextSize = 14
Instances.CloseButton_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.CloseButton_3.TextScaled = true
Instances.CloseButton_3.Parent = Instances.BSBD

Instances.DiscordButton_3.Name = "DiscordButton"
Instances.DiscordButton_3.Size = UDim2.new(0, 99, 0, 31)
Instances.DiscordButton_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton_3.Position = UDim2.new(-0.00189393945, 0, 0.877470374, 0)
Instances.DiscordButton_3.BorderSizePixel = 0
Instances.DiscordButton_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.DiscordButton_3.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton_3.Text = "Join Discord"
Instances.DiscordButton_3.TextWrapped = true
Instances.DiscordButton_3.TextSize = 14
Instances.DiscordButton_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.DiscordButton_3.TextScaled = true
Instances.DiscordButton_3.Parent = Instances.BSBD

Instances.SB_2.Name = "SB"
Instances.SB_2.Size = UDim2.new(0, 528, 0, 253)
Instances.SB_2.Visible = false
Instances.SB_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.SB_2.Position = UDim2.new(0.297628164, 0, 0.297770709, 0)
Instances.SB_2.BorderSizePixel = 0
Instances.SB_2.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.SB_2.Parent = Instances.UIs

Instances.B1_4.Name = "B1"
Instances.B1_4.Size = UDim2.new(0, 82, 0, 32)
Instances.B1_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1_4.Position = UDim2.new(0.288727283, 0, 0.0197628457, 0)
Instances.B1_4.BorderSizePixel = 0
Instances.B1_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B1_4.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B1_4.Text = "Anti-Cheat bypass (BETA)"
Instances.B1_4.TextWrapped = true
Instances.B1_4.TextSize = 14
Instances.B1_4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B1_4.TextScaled = true
Instances.B1_4.Parent = Instances.SB_2

Instances.LeftMenu_4.Name = "LeftMenu"
Instances.LeftMenu_4.Size = UDim2.new(0, 139, 0, 253)
Instances.LeftMenu_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.LeftMenu_4.BorderSizePixel = 0
Instances.LeftMenu_4.BackgroundColor3 = Color3.fromRGB(91, 91, 91)
Instances.LeftMenu_4.Parent = Instances.SB_2

Instances.TextButton_4.Name = "TextButton"
Instances.TextButton_4.Size = UDim2.new(0, 140, 0, 37)
Instances.TextButton_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton_4.Position = UDim2.new(-0.00104545825, 0, 0, 0)
Instances.TextButton_4.BorderSizePixel = 0
Instances.TextButton_4.BackgroundColor3 = Color3.fromRGB(190, 190, 190)
Instances.TextButton_4.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextButton_4.Text = "General"
Instances.TextButton_4.TextWrapped = true
Instances.TextButton_4.TextSize = 14
Instances.TextButton_4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextButton_4.TextScaled = true
Instances.TextButton_4.Parent = Instances.LeftMenu_4

Instances.UICorner_4.Name = "UICorner"
Instances.UICorner_4.Parent = Instances.SB_2

Instances.B2_3.Name = "B2"
Instances.B2_3.Size = UDim2.new(0, 82, 0, 32)
Instances.B2_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.B2_3.Position = UDim2.new(0.288727283, 0, 0.17786561, 0)
Instances.B2_3.BorderSizePixel = 0
Instances.B2_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.B2_3.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.B2_3.Text = "Make glove like extended"
Instances.B2_3.TextWrapped = true
Instances.B2_3.TextSize = 14
Instances.B2_3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.B2_3.TextScaled = true
Instances.B2_3.Parent = Instances.SB_2

Instances.TextLabel.Name = "TextLabel"
Instances.TextLabel.Size = UDim2.new(0, 227, 0, 32)
Instances.TextLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextLabel.Position = UDim2.new(1.13414633, 0, 0, 0)
Instances.TextLabel.BorderSizePixel = 0
Instances.TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.TextLabel.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextLabel.Text = "(Keep it in inventory when you clicking button)"
Instances.TextLabel.TextWrapped = true
Instances.TextLabel.TextSize = 14
Instances.TextLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextLabel.TextScaled = true
Instances.TextLabel.Parent = Instances.B2_3

Instances.CloseButton_4.Name = "CloseButton"
Instances.CloseButton_4.Size = UDim2.new(0, 18, 0, 22)
Instances.CloseButton_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.CloseButton_4.BackgroundTransparency = 1
Instances.CloseButton_4.Position = UDim2.new(0.965909064, 0, 0.0197628457, 0)
Instances.CloseButton_4.BorderSizePixel = 0
Instances.CloseButton_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.CloseButton_4.TextColor3 = Color3.fromRGB(255, 0, 0)
Instances.CloseButton_4.Text = "X"
Instances.CloseButton_4.TextWrapped = true
Instances.CloseButton_4.TextSize = 14
Instances.CloseButton_4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.CloseButton_4.TextScaled = true
Instances.CloseButton_4.Parent = Instances.SB_2

Instances.DiscordButton_4.Name = "DiscordButton"
Instances.DiscordButton_4.Size = UDim2.new(0, 99, 0, 31)
Instances.DiscordButton_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton_4.Position = UDim2.new(-0.00189393945, 0, 0.877470374, 0)
Instances.DiscordButton_4.BorderSizePixel = 0
Instances.DiscordButton_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.DiscordButton_4.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.DiscordButton_4.Text = "Join Discord"
Instances.DiscordButton_4.TextWrapped = true
Instances.DiscordButton_4.TextSize = 14
Instances.DiscordButton_4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.DiscordButton_4.TextScaled = true
Instances.DiscordButton_4.Parent = Instances.SB_2

Instances.TextLabel_2.Name = "TextLabel"
Instances.TextLabel_2.Size = UDim2.new(0, 200, 0, 50)
Instances.TextLabel_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextLabel_2.Position = UDim2.new(0.423118532, 0, 0.458915949, 0)
Instances.TextLabel_2.BorderSizePixel = 0
Instances.TextLabel_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.TextLabel_2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.TextLabel_2.Text = "wait please"
Instances.TextLabel_2.TextWrapped = true
Instances.TextLabel_2.TextSize = 14
Instances.TextLabel_2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.TextLabel_2.TextScaled = true
Instances.TextLabel_2.Parent = Instances.YE_HUB

Instances.tb1.Name = "tb1"
Instances.tb1.Size = UDim2.new(0, 99, 0, 31)
Instances.tb1.Visible = false
Instances.tb1.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.tb1.Position = UDim2.new(0, 0, 1, 0)
Instances.tb1.BorderSizePixel = 0
Instances.tb1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.tb1.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.tb1.Text = "Join Discord"
Instances.tb1.TextWrapped = true
Instances.tb1.TextSize = 14
Instances.tb1.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.tb1.TextScaled = true
Instances.tb1.Parent = Instances.TextLabel_2

Instances.tb2.Name = "tb2"
Instances.tb2.Size = UDim2.new(0, 101, 0, 31)
Instances.tb2.Visible = false
Instances.tb2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.tb2.Position = UDim2.new(0.495000005, 0, 1, 0)
Instances.tb2.BorderSizePixel = 0
Instances.tb2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.tb2.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.tb2.Text = "Ok close this window"
Instances.tb2.TextWrapped = true
Instances.tb2.TextSize = 14
Instances.tb2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.tb2.TextScaled = true
Instances.tb2.Parent = Instances.TextLabel_2

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B1)
	script.Parent.MouseButton1Click:Connect(function()
		local name = script.Parent.TextBox.Text
		for _, Player in ipairs(game.Players:GetPlayers()) do
			if Player.Character then
				for i, v in next, Player.Character:GetChildren() do
					if v:IsA("Model") then
						if v:FindFirstChild("ServerHandler") then
							v:FindFirstChild("ServerHandler"):FireServer(name)
						end
					end
				end
			end
		end
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B2)
	script.Parent.MouseButton1Click:Connect(function()
		fireclickdetector(workspace.Keycards["[SCP] Card-L5"].Handle.ClickDetector)
		fireclickdetector(workspace.Guns["AK-47"].Handle.ClickDetector)
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.SCPCBRP)
	local UserInputService = game:GetService("UserInputService")
	local runService = (game:GetService("RunService"));
	
	local gui = script.Parent
	
	local dragging
	local dragInput
	local dragStart
	local startPos
	
	function Lerp(a, b, m)
		return a + (b - a) * m
	end;
	
	local lastMousePos
	local lastGoalPos
	local DRAG_SPEED = (8); -- // The speed of the UI darg.
	function Update(dt)
		if not (startPos) then return end;
		if not (dragging) and (lastGoalPos) then
			gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, lastGoalPos.X.Offset, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, lastGoalPos.Y.Offset, dt * DRAG_SPEED))
			return 
		end;
	
		local delta = (lastMousePos - UserInputService:GetMouseLocation())
		local xGoal = (startPos.X.Offset - delta.X);
		local yGoal = (startPos.Y.Offset - delta.Y);
		lastGoalPos = UDim2.new(startPos.X.Scale, xGoal, startPos.Y.Scale, yGoal)
		gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, xGoal, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, yGoal, dt * DRAG_SPEED))
	end;
	
	gui.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = gui.Position
			lastMousePos = UserInputService:GetMouseLocation()
	
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragging = false
				end
			end)
		end
	end)
	
	gui.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	
	runService.Heartbeat:Connect(Update)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.CloseButton)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent.Parent:Destroy()
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B3)
	script.Parent.MouseButton1Click:Connect(function()
		local count = 0
		local num = tonumber(script.Parent.TextBox.Text)
		while wait() do
			if count<num then
				fireclickdetector(workspace.Keycards["[SCP] Card-L5"].Handle.ClickDetector)
				fireclickdetector(workspace.Guns["AK-47"].Handle.ClickDetector)
				count += 1
				print(count)
			else
				print('done')
				for i,v in pairs(game.Players.LocalPlayer.Backpack:GetChildren()) do
					v.Parent=game.Players.LocalPlayer.Character
				end
				break
			end
			
			
		end
		
		
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.DiscordButton)
	script.Parent.MouseButton1Click:Connect(function()
		setclipboard('https://discord.gg/22VyrEa8gs')
		script.Parent.Text='Discord copied'
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B1_2)
	script.Parent.MouseButton1Click:Connect(function()
		game.ReplicatedStorage.Events.KillEvent:FireServer()
	end)
	
	
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.EREPO)
	local UserInputService = game:GetService("UserInputService")
	local runService = (game:GetService("RunService"));
	
	local gui = script.Parent
	
	local dragging
	local dragInput
	local dragStart
	local startPos
	
	function Lerp(a, b, m)
		return a + (b - a) * m
	end;
	
	local lastMousePos
	local lastGoalPos
	local DRAG_SPEED = (8); -- // The speed of the UI darg.
	function Update(dt)
		if not (startPos) then return end;
		if not (dragging) and (lastGoalPos) then
			gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, lastGoalPos.X.Offset, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, lastGoalPos.Y.Offset, dt * DRAG_SPEED))
			return 
		end;
	
		local delta = (lastMousePos - UserInputService:GetMouseLocation())
		local xGoal = (startPos.X.Offset - delta.X);
		local yGoal = (startPos.Y.Offset - delta.Y);
		lastGoalPos = UDim2.new(startPos.X.Scale, xGoal, startPos.Y.Scale, yGoal)
		gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, xGoal, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, yGoal, dt * DRAG_SPEED))
	end;
	
	gui.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = gui.Position
			lastMousePos = UserInputService:GetMouseLocation()
	
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragging = false
				end
			end)
		end
	end)
	
	gui.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	
	runService.Heartbeat:Connect(Update)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.CloseButton_2)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent.Parent:Destroy()
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B2_2)
	script.Parent.MouseButton1Click:Connect(function()
		game.ReplicatedStorage.Events.SkipEndEvent:FireServer()
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B3_2)
	script.Parent.MouseButton1Click:Connect(function()
		while wait() do
			game.ReplicatedStorage.Events.SkipEndEvent:FireServer()
			game.ReplicatedStorage.Events.KillEvent:FireServer()
		end
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.DiscordButton_2)
	script.Parent.MouseButton1Click:Connect(function()
		setclipboard('https://discord.gg/22VyrEa8gs')
		script.Parent.Text='Discord copied'
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B1_3)
	script.Parent.MouseButton1Click:Connect(function()
		game.Players.LocalPlayer.PlayerScripts["Folder localscript and funny are anticheats that causes crash"]:Destroy()
		game.StarterPlayer.StarterPlayerScripts["Folder localscript and funny are anticheats that causes crash"]:Destroy()
	end)
	
	
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.BSBD)
	local UserInputService = game:GetService("UserInputService")
	local runService = (game:GetService("RunService"));
	
	local gui = script.Parent
	
	local dragging
	local dragInput
	local dragStart
	local startPos
	
	function Lerp(a, b, m)
		return a + (b - a) * m
	end;
	
	local lastMousePos
	local lastGoalPos
	local DRAG_SPEED = (8); -- // The speed of the UI darg.
	function Update(dt)
		if not (startPos) then return end;
		if not (dragging) and (lastGoalPos) then
			gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, lastGoalPos.X.Offset, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, lastGoalPos.Y.Offset, dt * DRAG_SPEED))
			return 
		end;
	
		local delta = (lastMousePos - UserInputService:GetMouseLocation())
		local xGoal = (startPos.X.Offset - delta.X);
		local yGoal = (startPos.Y.Offset - delta.Y);
		lastGoalPos = UDim2.new(startPos.X.Scale, xGoal, startPos.Y.Scale, yGoal)
		gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, xGoal, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, yGoal, dt * DRAG_SPEED))
	end;
	
	gui.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = gui.Position
			lastMousePos = UserInputService:GetMouseLocation()
	
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragging = false
				end
			end)
		end
	end)
	
	gui.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	
	runService.Heartbeat:Connect(Update)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.CloseButton_3)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent.Parent:Destroy()
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.DiscordButton_3)
	script.Parent.MouseButton1Click:Connect(function()
		setclipboard('https://discord.gg/22VyrEa8gs')
		script.Parent.Text='Discord copied'
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B1_4)
	script.Parent.MouseButton1Click:Connect(function()
		game.ReplicatedStorage.AdminGUI:Destroy()
		game.ReplicatedStorage.Ban:Destroy()
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.B2_3)
	script.Parent.MouseButton1Click:Connect(function()
		local glove = game.Players.LocalPlayer.Backpack:FindFirstChildWhichIsA('Tool')
		glove.Grip = CFrame.new(0, 0, 15)
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.SB_2)
	local UserInputService = game:GetService("UserInputService")
	local runService = (game:GetService("RunService"));
	
	local gui = script.Parent
	
	local dragging
	local dragInput
	local dragStart
	local startPos
	
	function Lerp(a, b, m)
		return a + (b - a) * m
	end;
	
	local lastMousePos
	local lastGoalPos
	local DRAG_SPEED = (8); -- // The speed of the UI darg.
	function Update(dt)
		if not (startPos) then return end;
		if not (dragging) and (lastGoalPos) then
			gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, lastGoalPos.X.Offset, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, lastGoalPos.Y.Offset, dt * DRAG_SPEED))
			return 
		end;
	
		local delta = (lastMousePos - UserInputService:GetMouseLocation())
		local xGoal = (startPos.X.Offset - delta.X);
		local yGoal = (startPos.Y.Offset - delta.Y);
		lastGoalPos = UDim2.new(startPos.X.Scale, xGoal, startPos.Y.Scale, yGoal)
		gui.Position = UDim2.new(startPos.X.Scale, Lerp(gui.Position.X.Offset, xGoal, dt * DRAG_SPEED), startPos.Y.Scale, Lerp(gui.Position.Y.Offset, yGoal, dt * DRAG_SPEED))
	end;
	
	gui.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = gui.Position
			lastMousePos = UserInputService:GetMouseLocation()
	
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragging = false
				end
			end)
		end
	end)
	
	gui.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	
	runService.Heartbeat:Connect(Update)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.CloseButton_4)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent.Parent:Destroy()
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.DiscordButton_4)
	script.Parent.MouseButton1Click:Connect(function()
		setclipboard('https://discord.gg/22VyrEa8gs')
		script.Parent.Text='Discord copied'
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.TextLabel_2)
	local gameid = game.GameId
	
	if gameid==331652222 then
		script.Parent.Parent.UIs.SCPCBRP.Visible=true
		script.Parent:Destroy()
	elseif gameid==1276616222 then
		script.Parent.Parent.UIs.EREPO.Visible=true
		script.Parent:Destroy()
	elseif gameid==2380077519 then
		script.Parent.Parent.UIs.SB.Visible=true
		script.Parent:Destroy()
	else
		script.Parent.Text='This game is not supported.'
		script.Parent.tb1.Visible=true
		script.Parent.tb2.Visible=true
	end
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.tb1)
	script.Parent.MouseButton1Click:Connect(function()
		setclipboard('https://discord.gg/22VyrEa8gs')
		script.Parent.Text='Discord copied'
	end)
end)

-- Function "LocalScript"
task.spawn(function()
	local script = Instance.new("LocalScript", Instances.tb2)
	script.Parent.MouseButton1Click:Connect(function()
		script.Parent.Parent.Parent:Destroy()
	end)
end)

--[[ End of generation. ]]
